### ISSUE TITLE
Code Quality: AutonomousAirdrop.sol has unused variables

### ISSUE THREAD

**Issue by Braqzen** [axiom-crypto/old-autonomous-airdrop-example#21]
Forewarning: it's my first time looking at axiom and I'm completely ignorant so bare with me as I learn a little.

## Context

I'm looking through the repository to piece together what is happening.
Having reached `AutonomousAirdrop.sol` I've noticed that there are some variables that are unimplemented / unused and it's a little confusing because it's unclear if they are relevant or not.

Given that the airdrop is constrained by the interface of the v2 client it would be helpful if all of the features were implemented rather than left unused because it would be easier to infer what the infra / design is when looking at the usage of all of the components in the code.

## Unimplemented code

The following sections are unused and may be considered for removal or implementation.

### Events

**ClaimAirdropError**

https://github.com/axiom-crypto/autonomous-airdrop-example/blob/d2889b917de5053619ea8829ba4c0551663fba2e/contracts/src/AutonomousAirdrop.sol#L15C1-L18

I would turn this into an error rather than an event but I don't know what the design is yet.

### Mappings

**querySubmitted**

https://github.com/axiom-crypto/autonomous-airdrop-example/blob/d2889b917de5053619ea8829ba4c0551663fba2e/contracts/src/AutonomousAirdrop.sol#L27C37-L27C51

## Functions

**_axiomV2Callback** has unused parameters: `querySchema` & `extraData`

https://github.com/axiom-crypto/autonomous-airdrop-example/blob/d2889b917de5053619ea8829ba4c0551663fba2e/contracts/src/AutonomousAirdrop.sol#L53-L60

**_validateAxiomV2Call** has an unused parameter: `callerAddr`

https://github.com/axiom-crypto/autonomous-airdrop-example/blob/d2889b917de5053619ea8829ba4c0551663fba2e/contracts/src/AutonomousAirdrop.sol#L88-L92

**Comment by ytham** [comment]
thanks; fixed in https://github.com/axiom-crypto/autonomous-airdrop-example/commit/86c1999a252df5d78062df1f1e14ca18baeffcb3
